sudo: required
services:
  - docker

before_install:
  - docker build -t mephisto2120/sw-matcher-client -f Dockerfile.dev .

script:
  - docker run mephisto2120/sw-matcher-client npm run test -- --coverage